Lab 08/Lab06/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab06.Infrastructure;
using Lab06.Models;
using Lab06.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Lab06.Controllers
{
    public class ReviewController : Controller
    {
        private IEmployeeRepository repository;
        private Review review;

        public ReviewController(IEmployeeRepository repo, Review reviewService)
        {
            repository = repo;
            review = reviewService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new ReviewIndexViewModel
            {
                Review = review,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddEmployee(int employeeId, string returnUrl)
        {
            Employee employee = repository.Employees
                .FirstOrDefault(e => e.EmployeeId == employeeId);

            

            if (employee != null)
            {
                review.AddEmployee(employee);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveEmployee(int employeeId, string returnUrl)
        {
            Employee employee = repository.Employees
                .FirstOrDefault(e => e.EmployeeId == employeeId);

            if (employee != null)
            {
                review.RemoveEmployee(employee);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        
    }
}

Lab 08/Lab06/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab06.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab06.Controllers
{
    public class SubmissionController : Controller
    {
        private ISubmissionRepository repository;
        private Review review;

        public SubmissionController(ISubmissionRepository repoService, Review reviewService)
        {
            repository = repoService;
            review = reviewService;
        }

        public ViewResult List() =>
            View(repository.Submissions.Where(s => !s.Completed));

        [HttpPost]
        public IActionResult MarkCompleted(int submissionId)
        {
            Submission submission = repository.Submissions
                .FirstOrDefault(s => s.SubmissionID == submissionId);
            if (submission != null)
            {
                submission.Completed = true;
                repository.SaveSubmission(submission);
            }
            return RedirectToAction(nameof(List));
        }


        public ViewResult Submit() => View(new Submission());

        [HttpPost]
        public IActionResult Submit(Submission submission)
        {
            if (review.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, there are no employees selected for review!");
            }
            if (ModelState.IsValid)
            {
                submission.Lines = review.Lines.ToArray();
                repository.SaveSubmission(submission);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(submission);
            }
        }

        public ViewResult Completed()
        {
            review.Clear();
            return View();
        }
    }
}

Lab 08/Lab06/Views/Review/Index.cshtml
@model ReviewIndexViewModel

<h2>Employees Selected For Review</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Employee ID:</th>
            <th>Employee Name:</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Review.Lines)
        { 
        <tr>
            <td class="text-center">@line.Employee.EmployeeId</td>
            <td class="text-center">@line.Employee.FirstName @line.Employee.LastName</td>
            <td>
                <form asp-action="RemoveEmployee" method="post">
                    <input type="hidden" name="EmployeeId"
                           value="@line.Employee.EmployeeId"/>
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl"/>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>

        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Go Back To Employees</a>
    <a class="btn btn-primary" asp-action="Submit" asp-controller="Submission">
        Submit For Review(s)
    </a>

</div>